version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=ems-fullstack
      - POSTGRES_PASSWORD=123456a@
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d 'user=${MYSQL_USER} dbname=${MYSQL_DATABASE}'" ]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    container_name: api
    build:
      context: ./api
      args:
        progress: plain
    ports:
      - "8080:8081"

volumes:
  db:
    driver: local