version: '3.8'
services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=ems-fullstack
      - POSTGRES_PASSWORD=123456a@
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d 'user=ems-fullstack dbname=123456a@'" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ems-network

  api:
    container_name: api
    build:
      context: .
      args:
        progress: plain
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      - POSTGRESQL_CONTAINER_NAME=db
    networks:
      - ems-network

volumes:
  db:
    driver: local

networks:
  ems-network:
    name: ems
    external: true